name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: 'major'
        minor_pattern: 'feat'
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version

    - name: Docker login
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker image
      env:
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t carlospalacin/graphql-actions:$VERSION .
        docker build -t carlospalacin/graphql-actions:latest .

    - name: Push Docker image
      env:
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push carlospalacin/graphql-actions:$VERSION
        docker push carlospalacin/graphql-actions:latest

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
